Repository rrickfox/traffic-sim, pull requests merged in 2020-03, with the labels that each got.

#96 Feature/unique-cars
  Assets/Scripts/DataTypes/Car.cs
Labels: enhancement

#103 improve how constants are used
  Assets/Scripts/DataTypes/Car.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/GameObjectData.cs
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/DataTypes/Vertices/Roundabout.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/Saves/Serializers.cs
  Assets/Scripts/Utility/CONSTANTS.cs
Labels: enhancement

#108 Change weights to be a dictionary
  Assets/Saves/sample.yaml
  Assets/Saves/single_street.yaml
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/Saves/Serializers.cs
  Assets/Scripts/Utility/MathUtils.cs
  Assets/Scripts/Utility/Random.cs
Labels: bug, enhancement, high priority

#110 fix nullreference
  Assets/Scenes/simulation.unity
  Assets/Scripts/Interface/UIElements.meta
Labels: bug, high priority

#86 Feature/intersections
  Assets/Scripts/DataTypes/Car/Car.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/Edges/RoadShape.cs
  Assets/Scripts/DataTypes/Edges/RouteSegment.cs
  Assets/Scripts/DataTypes/Edges/SectionTrack.cs
  Assets/Scripts/DataTypes/Edges/SectionTrack.cs.meta
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/Pathfinding/Pathfinding.cs
  Assets/Scripts/Utility/COLORS.cs
  Assets/Scripts/Utility/CONSTANTS.cs
Labels: enhancement

#102 Feature/car 3d model
  Assets/Resources/Car-Prefab.prefab
  Assets/Resources/Car-Prefab.prefab.meta
  Assets/Resources/car.fbx
  Assets/Resources/car.fbx.meta
  Assets/Scripts/Utility/CONSTANTS.cs
Labels: enhancement

#107 feature/fix-car-ai
  Assets/Saves/four_sections.yaml
  Assets/Saves/four_sections.yaml.meta
  Assets/Scenes/simulation.unity
  Assets/Scripts/DataTypes/Car/Car.cs
  Assets/Scripts/DataTypes/Car/Drivers/NormalDriver.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/Interface/CarStats.cs
  Assets/Scripts/Pathfinding/Pathfinding.cs
  Assets/Scripts/Utility/Formulas.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement, in development

#113 Add speedLimit to yaml-file
  Assets/Saves/four_sections.yaml
  Assets/Saves/sample.yaml
  Assets/Saves/single_street.yaml
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/Saves/Serializers.cs
Labels: enhancement

#97 Add traffic lights
  Assets/Resources/Ampel.fbx
  Assets/Resources/Ampel.fbx.meta
  Assets/Resources/Car-Prefab.prefab
  Assets/Saves/four_sections.yaml
  Assets/Saves/sample.yaml
  Assets/Scenes/simulation.unity
  Assets/Scripts/DataTypes/Car/Car.cs
  Assets/Scripts/DataTypes/Car/Drivers/NormalDriver.cs
  Assets/Scripts/DataTypes/Car/Drivers/TrafficLightDriver.cs
  Assets/Scripts/DataTypes/Car/Drivers/TrafficLightDriver.cs.meta
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/Edges/ITrack.cs
  Assets/Scripts/DataTypes/Edges/SectionTrack.cs
  Assets/Scripts/DataTypes/GameObjectData.cs
  Assets/Scripts/DataTypes/TrafficLight.cs
  Assets/Scripts/DataTypes/TrafficLight.cs.meta
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/Events/ObjectPublisher.cs
  Assets/Scripts/Saves/Serializers.cs
  Assets/Scripts/Utility/Formulas.cs
  packages.config
  packages.config.meta
Labels: enhancement, in development

#116 fix formula changes
  Assets/Scripts/Utility/Formulas.cs
Labels: bug, high priority

#117 fix formula
  Assets/Scripts/Utility/Formulas.cs
Labels: bug, high priority
