Repository rrickfox/traffic-sim, pull requests merged in 2020-01, with the labels that each got.

#16 Feature/datastructure
  .gitignore
  Assets/NuGet.config
  Assets/NuGet.config.meta
  Assets/Packages.meta
  Assets/Plugins.meta
  Assets/Plugins/NuGet.meta
  Assets/Plugins/NuGet/Editor.meta
  Assets/Plugins/NuGet/Editor/DotNetZip.dll
  Assets/Plugins/NuGet/Editor/DotNetZip.dll.meta
  Assets/Plugins/NuGet/Editor/NugetForUnity.dll
  Assets/Plugins/NuGet/Editor/NugetForUnity.dll.meta
  Assets/Plugins/NuGet/LICENSE
  Assets/Plugins/NuGet/LICENSE.meta
  Assets/Plugins/NuGet/Resources.meta
  Assets/Plugins/NuGet/Resources/defaultIcon.png
  Assets/Plugins/NuGet/Resources/defaultIcon.png.meta
  Assets/Scripts/DataTypes/CrossSection.cs
  Assets/Scripts/DataTypes/Edges.meta
  Assets/Scripts/DataTypes/Edges/Anchor.cs
  Assets/Scripts/DataTypes/Edges/Anchor.cs.meta
  Assets/Scripts/DataTypes/Edges/AnchorNumber.cs
  Assets/Scripts/DataTypes/Edges/AnchorNumber.cs.meta
  Assets/Scripts/DataTypes/Edges/Lane.cs
  Assets/Scripts/DataTypes/Edges/Lane.cs.meta
  Assets/Scripts/DataTypes/Edges/Road.cs
  Assets/Scripts/DataTypes/Edges/Road.cs.meta
  Assets/Scripts/DataTypes/Edges/RoadShape.cs
  Assets/Scripts/DataTypes/Edges/RoadShape.cs.meta
  Assets/Scripts/DataTypes/Node.cs
  Assets/Scripts/DataTypes/Node.cs.meta
  Assets/Scripts/DataTypes/Road.cs
  Assets/Scripts/DataTypes/Roundabout.cs
  Assets/Scripts/DataTypes/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices.meta
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs.meta
  Assets/Scripts/DataTypes/Vertices/Roundabout.cs
  Assets/Scripts/DataTypes/Vertices/Roundabout.cs.meta
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs.meta
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs.meta
  Assets/packages.config
  Assets/packages.config.meta
Labels: high priority

#33 replace Road and Anchor with Edge (inheriting from RoadView)
  Assets/Scripts/DataTypes/Car.cs
  Assets/Scripts/DataTypes/Edges/Anchor.cs
  Assets/Scripts/DataTypes/Edges/Anchor.cs.meta
  Assets/Scripts/DataTypes/Edges/AnchorNumber.cs
  Assets/Scripts/DataTypes/Edges/AnchorNumber.cs.meta
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs.meta
  Assets/Scripts/DataTypes/Edges/Point.cs
  Assets/Scripts/DataTypes/Edges/Point.cs.meta
  Assets/Scripts/DataTypes/Edges/Road.cs
  Assets/Scripts/DataTypes/Edges/RoadView.cs
  Assets/Scripts/DataTypes/Edges/RoadView.cs.meta
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/Roundabout.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
Labels: high priority

#43 fix rotation bug of cars and road
  Assets/Scripts/CarSpawner.cs
  Assets/Scripts/RoadSpawner.cs
Labels: bug, high priority

#44 add ability to control spawnrate & endpoints of road in the editor
  Assets/Scenes/simulation.unity
  Assets/Scripts/SimulationController.cs
Labels: enhancement

#47 Cleanup
  Assets/Scripts/CONSTANTS.cs
  Assets/Scripts/Cameras/FreeCamera.cs
  Assets/Scripts/CarDespawner.cs
  Assets/Scripts/CarSpawner.cs
  Assets/Scripts/Conversion.cs
  Assets/Scripts/DataTypes/Car.cs
  Assets/Scripts/DataTypes/CarId.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs.meta
  Assets/Scripts/DataTypes/Edges/RoadView.cs
  Assets/Scripts/DataTypes/Edges/RoadView.cs.meta
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/RoadSpawner.cs
  Assets/Scripts/SimulationController.cs
Labels: high priority

#52 allow calling the Vertex constructor with any number of edges which are automatically converted to an array
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
Labels: enhancement
