Repository rrickfox/traffic-sim, pull requests merged in 2020-02, with the labels that each got.

#60 fix usage of other before it was constructed
  Assets/Scripts/DataTypes/Edges/Edge.cs
Labels: bug, high priority

#61 Feature/behaviour modularity
  Assets/Scripts/DataTypes/Car.cs
  Assets/Scripts/DataTypes/CarId.cs
  Assets/Scripts/DataTypes/Edges/Edge.cs
  Assets/Scripts/DataTypes/Frequencies.cs
  Assets/Scripts/DataTypes/Frequencies.cs.meta
  Assets/Scripts/DataTypes/GameObjectData.cs
  Assets/Scripts/DataTypes/GameObjectData.cs.meta
  Assets/Scripts/DataTypes/LinkedBehaviour.cs
  Assets/Scripts/DataTypes/LinkedBehaviour.cs.meta
  Assets/Scripts/DataTypes/Vertices/CrossSection.cs
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/DataTypes/Vertices/Roundabout.cs
  Assets/Scripts/DataTypes/Vertices/TeeSection.cs
  Assets/Scripts/DataTypes/Vertices/Vertex.cs
  Assets/Scripts/Pathfinding.meta
  Assets/Scripts/Pathfinding/Pathfinding.cs
  Assets/Scripts/Pathfinding/Pathfinding.cs.meta
  Assets/Scripts/RoadSpawner.cs
  Assets/Scripts/RoadSpawner.cs.meta
  Assets/Scripts/SimulationController.cs
  Assets/Scripts/Utility/CONSTANTS.cs
Labels: high priority

#68 remove roadPrefab from EndPoint
  Assets/Scripts/DataTypes/Vertices/EndPoint.cs
  Assets/Scripts/SimulationController.cs
Labels: bug

#78 delete bezier scene and pointplacer script
  Assets/Scenes/bezier.unity
  Assets/Scenes/bezier.unity.meta
  Assets/Scripts/PointPlacer.cs
  Assets/Scripts/PointPlacer.cs.meta
Labels: bug
